{{ if and .Values.rbac.create .Values.rbac.createrole }}
apiVersion: rbac.authorization.k8s.io/v1
kind:  {{ if not .Values.rbac.namespaced -}} Cluster {{- end -}} Role
metadata:
  name: vault-secrets-operator
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "vault-secrets-operator.labels" . | indent 4 }}
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ricoberger.de
  resources:
  - vaultsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ricoberger.de
  resources:
  - vaultsecrets/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ricoberger.de
  resources:
  - vaultsecrets/status
  verbs:
  - get
  - patch
  - update
{{ end }}
