---
version: "2"
run:
  modules-download-mode: readonly
linters:
  default: none
  enable:
    - bodyclose
    - gosec
    - govet
    - ineffassign
    - noctx
    - staticcheck
    - unused
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/ricoberger/vault-secrets-operator
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
