{
 "title": "Vault Secrets Operator",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "VaultSecrets Reconciliation Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(vaultsecrets_reconciliation_status) by (namespace, name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reconciliation Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{controller=\"vaultsecret\"}[2m])) by (result)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reconciliation Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_time_seconds_sum{controller=\"vaultsecret\"}[2m])) / sum(rate(controller_runtime_reconcile_time_seconds_count{controller=\"vaultsecret\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workqueue - Queue Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_queue_duration_seconds_sum{name=\"vaultsecret\"}[2m])) / sum(rate(workqueue_queue_duration_seconds_count{name=\"vaultsecret\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workqueue - Work Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_work_duration_seconds_sum{name=\"vaultsecret\"}[2m])) / sum(rate(workqueue_work_duration_seconds_count{name=\"vaultsecret\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}